name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-php:
    name: PHP Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP Linter
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

  lint-js:
    name: JavaScript Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install ESLint
        run: |
          npm install --save-dev eslint
          npx eslint --init

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

